apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stress-ng-pvc
  namespace: default
spec:
  storageClassName: longhorn-v2-data-engine
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: stress-ng
spec:
  restartPolicy: Always
  containers:
  - name: stress-ng
    image: docker.io/derekbit/volume-stressor:latest
    env:
      - name: HDD
        value: "1"
      - name: HDD_BYTES
        value: "4G"
      - name: TEMP_PATH
        value: "/data"
    volumeMounts:
    - name: stress-ng-vol
      mountPath: /data
  volumes:
  - name: stress-ng-vol
    persistentVolumeClaim:
      claimName: stress-ng-pvc
